export const SET_ONBOARD = 'SET_ONBOARD';
export const SET_TALENT_INFO = 'SET_TALENT_INFO';

export const START_NATIVE_LOCAL_RECORDING = 'START_NATIVE_LOCAL_RECORDING';

export const STOP_NATIVE_LOCAL_RECORDING = 'STOP_NATIVE_LOCAL_RECORDING';

export const ADD_NATIVE_LOCAL_RECORDING = 'ADD_NATIVE_LOCAL_RECORDING';

export const REMOVE_NATIVE_LOCAL_RECORDING = 'REMOVE_NATIVE_LOCAL_RECORDING';

export const UPLOAD_NATIVE_LOCAL_RECORDING_START = 'UPLOAD_NATIVE_LOCAL_RECORDING_START';

export const UPLOAD_NATIVE_LOCAL_RECORDING_FINISH = 'UPLOAD_NATIVE_LOCAL_RECORDING_FINISH';

export const UPDATE_LOCAL_RECORDING_STATUS = 'UPDATE_LOCAL_RECORDING_STATUS';

export const SET_CURRENT_RECORDING_PATH = 'SET_CURRENT_RECORDING_PATH';

export const SET_LOCAL_RECORD_AUTO_UPLOAD = 'SET_LOCAL_RECORD_AUTO_UPLOAD';

export const SET_CLIPBOARD_DATA = 'SET_CLIPBOARD_DATA';

export const SET_ENABLE_1080P = 'SET_ENABLE_1080P';

export const UPDATE_UPLOAD_PROGRESS = 'UPDATE_UPLOAD_PROGRESS';

export const SET_UPLOAD_ERROR = 'SET_UPLOAD_ERROR';